receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"

exporters:
  logging:

processors:
  batch:
  devmode:

extensions:
  pprof:
  zpages:
    endpoint: "localhost:55679"
  devmode:

service:
  extensions: [pprof, zpages, devmode]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [devmode, batch]
      exporters: [logging]
