receivers:
  otlp:
    protocols:
      grpc:
  zipkin:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

processors:
  batch:
  devmode:

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: ":55679"
  devmode:

service:
  extensions: [pprof, zpages, health_check, devmode]
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [zipkin, jaeger, logging]
      processors: [devmode, batch]
