receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

processors:
  batch:
  devmode:

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: ":55679"
  devmode:

service:
  extensions: [pprof, zpages, health_check, devmode]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [devmode, batch]
      exporters: [logging]
